using System.Collections.Generic;

namespace WebUIToolkit.MVVM.Flow.Tests.WaveB;

internal static class WaveBTestCatalog
{
    public static IReadOnlyList<ContractTest> All { get; } =
    [
        new("content-session ancestor ownership cycles are rejected", SessionHierarchyTests.AncestorCycleIsRejectedBeforeOwnershipChanges),
        new("checkpoint envelopes defensively copy mutable inputs", CheckpointTests.EnvelopeDefensivelyCopiesInputs),
        new("checkpoint envelopes reject invalid format, schema, and payload bounds", CheckpointTests.EnvelopeRejectsInvalidBounds),
        new("checkpoint restore accepts valid repeated history", CheckpointTests.ValidEnvelopeRoundTripsThroughValidation),
        new("checkpoint restore rejections are deterministic", CheckpointTests.RestoreRejectionsAreDeterministic),
        new("checkpoint migration runs once and its result is revalidated", CheckpointTests.MigrationRunsOnceAndIsRevalidated),
        new("checkpoint migration observes caller cancellation", CheckpointTests.MigrationObservesCallerCancellation),
        new("generated valid checkpoint histories preserve their values", CheckpointTests.GeneratedValidEnvelopesPreserveHistory),
        new("checkpoint restore rejects empty or inconsistent history", CheckpointTests.RestoreRejectsEmptyOrInconsistentHistory),
        new("operation success publishes ordered clock-based snapshots and progress", OperationTests.SuccessPublishesOrderedSnapshotsAndProgress),
        new("invalid operation progress fractions fault without escaping bounds", OperationTests.InvalidProgressFractionsFaultWithoutEscapingBounds),
        new("operation queue is FIFO and queued cancellation skips work", OperationTests.QueueIsFifoAndQueuedCancellationSkipsWork),
        new("operation reject policy invokes neither work nor presenter", OperationTests.RejectNeverInvokesWorkOrPresenter),
        new("operation CancelPrevious waits for prior cleanup", OperationTests.CancelPreviousWaitsForPriorCleanup),
        new("operation timeout uses the supplied manual clock", OperationTests.TimeoutUsesManualClock),
        new("concurrent operation progress reports remain consistent", OperationTests.ConcurrentProgressReportsRemainConsistent),
        new("operation presenter cleanup failure obeys precedence", OperationTests.PresenterCleanupFailureObeysPrecedence),
        new("operation hung presenter cleanup releases its slot after manual timeout", OperationTests.HungPresenterCleanupReleasesSlotAfterManualTimeout),
        new("workflow builder rejects invalid graphs", WorkflowTests.BuilderRejectsInvalidGraphs),
        new("workflow conditional steps skip and retained history reuses scopes", WorkflowTests.ConditionalStepsAreSkippedAndRetainedHistoryIsReused),
        new("workflow validation failure stays without commit or presentation", WorkflowTests.ValidationFailureStaysWithoutCommitOrPresentation),
        new("workflow commit and presenter faults leave current snapshot", WorkflowTests.CommitAndPresenterFaultsLeaveCurrentSnapshot),
        new("workflow finish factory retries after fault and completes once", WorkflowTests.FinishFactoryMayRetryAfterFaultAndCompletesOnce),
        new("workflow cancel guard denial can be bypassed by shutdown", WorkflowTests.CancelGuardDenialCanBeBypassedByShutdown),
        new("concurrent workflow transitions are serialized", WorkflowTests.ConcurrentTransitionsAreSerialized),
        new("excluded workflow redirect loop preserves current step", WorkflowTests.ExcludedRedirectLoopFaultsWithoutChangingCurrentStep),
        new("workflow branch selection observes context after commit", WorkflowTests.BranchSelectionUsesContextAfterCommit),
        new("workflow Finish deactivates exactly once in order", WorkflowTests.FinishDeactivatesExactlyOnceInOrder),
        new("workflow Stay after finish fault resets preparation phase", WorkflowTests.StayAfterFinishFaultResetsPreparationPhase),
        new("workflow hung lease close abandons dependent teardown", WorkflowTests.HungLeaseCloseAbandonsDependentTeardown),
        new("dialog completion races select exactly one typed outcome", DialogTests.ConcurrentCompletionSelectsExactlyOneOutcome),
        new("dialog guard denial releases the completion claim for retry", DialogTests.GuardDenialReleasesClaimForRetry),
        new("dialog caller cancellation requests an outcome and still cleans up", DialogTests.CallerCancellationRequestsOutcomeAndStillCleansUp),
        new("dialog teardown order is deterministic", DialogTests.TeardownOrderIsDeterministic),
        new("dialog accepted outcome survives close-failure metadata", DialogTests.AcceptedOutcomeSurvivesCloseFailureMetadata),
        new("dialog presenter open failure disposes pre-commit content", DialogTests.PresenterOpenFailureDisposesPreCommitContent),
        new("dialog shutdown bypasses guards and rejects new dialogs", DialogTests.ShutdownBypassesGuardAndRejectsNewDialogs),
        new("dialog shutdown drains a pending guard before disposal", DialogTests.ShutdownWaitsForPendingGuardBeforeDisposal),
        new("dialog caller cancellation during initialization returns after cleanup", DialogTests.CallerCancellationDuringInitializationReturnsOutcomeAfterCleanup),
        new("dialog registration rejects ambiguous actions", DialogTests.RegistrationRejectsAmbiguousActions),
        new("dialog registration rejects default logical identities", DialogTests.RegistrationRejectsDefaultLogicalIdentities),
        new("dialog hung lease close times out with accepted outcome", DialogTests.HungLeaseCloseTimesOutWithAcceptedOutcome),
        new("navigation start, push, replace, reset, and clear commit expected stacks", NavigationTests.StartPushReplaceResetAndClearCommitExpectedStacks),
        new("navigation Back retains or recreates according to registration", NavigationTests.BackRetainsOrRecreatesAccordingToRegistration),
        new("navigation guard denial creates and presents no target", NavigationTests.GuardDenialDoesNotCreateOrPresentTarget),
        new("navigation presenter failure rolls back and disposes target", NavigationTests.PresenterFailureRollsBackAndDisposesTarget),
        new("navigation queue is FIFO and queued cancellation removes request", NavigationTests.QueueIsFifoAndQueuedCancellationRemovesRequest),
        new("navigation reject-while-busy skips target factory", NavigationTests.RejectWhileBusyReturnsBusyWithoutFactory),
        new("navigation reentrant guard mutation preserves snapshot", NavigationTests.ReentrantGuardMutationThrowsAndPreservesSnapshot),
        new("navigation stale events and shutdown cannot mutate state", NavigationTests.StaleEventsAndShutdownCannotMutateState),
        new("navigation hung lease close is bounded by manual clock", NavigationTests.HungLeaseCloseIsBoundedByManualClock),
        new("Flow generator diagnostic catalog is ordered and stable", GeneratorContractTests.DiagnosticCatalogIsOrderedAndStable),
        new("Flow generator emission is culture and line-ending independent", GeneratorContractTests.EmissionIsCultureAndLineEndingIndependent),
        new("Flow generator identifier collisions and hint names are deterministic", GeneratorContractTests.IdentifierCollisionsAndHintNamesAreDeterministic),
    ];
}
